//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dress.DAL.Structure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerResult
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string VideoUrl { get; set; }
        public string CustomerName { get; set; }
        public string ImageGroupUrl { get; set; }
        public string ServiceName { get; set; }
        public string ImageBeforeUrl { get; set; }
        public string ImageAfterUrl { get; set; }
        public Nullable<int> IndexImage { get; set; }
    }
}
