//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dress.DAL.Structure
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationReference
    {
        public int Id { get; set; }
        public int ServiceDetails_ID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string LogoUrl { get; set; }
        public Nullable<int> Index { get; set; }
    }
}
