//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dress.DAL.Structure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hkv00123_BeautySalonEntities : DbContext
    {
        public hkv00123_BeautySalonEntities()
            : base("name=hkv00123_BeautySalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<CustomerResult> CustomerResults { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<GroupPost> GroupPosts { get; set; }
        public virtual DbSet<HighlightService> HighlightServices { get; set; }
        public virtual DbSet<InformationReference> InformationReferences { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<ProcessSurgery> ProcessSurgeries { get; set; }
        public virtual DbSet<ServiceDetail> ServiceDetails { get; set; }
        public virtual DbSet<ServiceReference> ServiceReferences { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Navigation> Navigations { get; set; }
        public virtual DbSet<ImageHome> ImageHomes { get; set; }
        public virtual DbSet<Salon> Salons { get; set; }
        public virtual DbSet<NewsArticle> NewsArticles { get; set; }
        public virtual DbSet<NewsInfoRefer> NewsInfoRefers { get; set; }
        public virtual DbSet<NewsServiceRefer> NewsServiceRefers { get; set; }
    }
}
