//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dress.DAL.Structure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigation
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public Nullable<int> Parent { get; set; }
        public string Group { get; set; }
    }
}
