//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dress.DAL.Structure
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsArticle
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Content1 { get; set; }
        public string Image1_Url { get; set; }
        public string Content2 { get; set; }
        public string Image2_Url { get; set; }
        public string Content3 { get; set; }
        public string Image3_Url { get; set; }
        public string Content4 { get; set; }
        public string Image4_1_Url { get; set; }
        public string Image4_2_Url { get; set; }
        public string Image4_3_Url { get; set; }
        public string Image4_4_Url { get; set; }
        public string Image1_Mobile_Url { get; set; }
        public string Image2_Mobile_Url { get; set; }
        public string Image3_Mobile_Url { get; set; }
        public string Image4_1_Mobile_Url { get; set; }
        public string Image4_2_Mobile_Url { get; set; }
        public string Image4_3_Mobile_Url { get; set; }
        public string Image4_4_Mobile_Url { get; set; }
    }
}
