//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dress.DAL.Structure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salon
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Youtube_Url { get; set; }
        public string Logo_Url { get; set; }
        public string Zalo_Url { get; set; }
        public string Facebook_Url { get; set; }
        public string Instagram_Url { get; set; }
        public string TickToc_Url { get; set; }
        public string HotLine { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string Slogen { get; set; }
        public string Owner { get; set; }
        public string Email { get; set; }
        public string WorkHour { get; set; }
    }
}
