//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dress.DAL.Structure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Title1 { get; set; }
        public string Content1 { get; set; }
        public string Title2 { get; set; }
        public string Content2 { get; set; }
        public string Title3 { get; set; }
        public string Title4 { get; set; }
        public string Title5 { get; set; }
        public string Title6 { get; set; }
        public string Title7 { get; set; }
        public string SearchKey { get; set; }
        public Nullable<int> NumberOfObjects { get; set; }
    }
}
